language: cpp
dist: xenial
sudo: required

#compiler: gcc

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    - os: windows

    - os: osx
      osx_image: xcode11

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - cmake --build .
#  - cmake --build . -- -j 2
  - ./tests/tileson_tests