name: Windows (MSVC)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Windows:
    runs-on: windows-2019
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - uses: actions/checkout@v2

      - name: Make build folder
        working-directory: ${{github.workspace}}
        run: mkdir build

      - name: CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../ -G "Visual Studio 15 2017 Win64"

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: tests/Debug/tileson_tests.exe --order rand